source 'http://rubygems.org'

gem 'dotenv-rails'
gem 'rails', '4.1.0'
gem 'pg'
gem 'dynamic_form'
gem 'exception_notification'
gem 'bcrypt'
gem "paperclip", "~> 3.0"
gem "therubyracer", :require => 'v8'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'sass-rails',   '~> 4.0.0'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'paperclip', '~> 3.0'
gem 'aws-sdk', '~> 1.5.7'
gem 'nested_form'
